// <auto-generated />
using System;
using ControleGestaoFtth.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleGestaoFtth.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ControleGestaoFtth.Models.Construtora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AceitacaoData")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AceitacaoMesRef")
                        .HasColumnType("longtext");

                    b.Property<int?>("BobinadeLancamento")
                        .HasColumnType("int");

                    b.Property<int?>("BobinadeRecepcao")
                        .HasColumnType("int");

                    b.Property<string>("CDO")
                        .HasColumnType("longtext");

                    b.Property<string>("CHAVE")
                        .HasColumnType("longtext");

                    b.Property<int?>("Cabo")
                        .HasColumnType("int");

                    b.Property<int?>("Capacidade")
                        .HasColumnType("int");

                    b.Property<int?>("Celula")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DatadeConstrucao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DatadeRecebimento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DatadoTeste")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext");

                    b.Property<string>("EquipedeConstrucao")
                        .HasColumnType("longtext");

                    b.Property<int?>("EstacoesId")
                        .HasColumnType("int");

                    b.Property<int?>("EstadoCamposId")
                        .HasColumnType("int");

                    b.Property<string>("FibraDGO")
                        .HasColumnType("longtext");

                    b.Property<string>("Meta")
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<string>("PosicaoICX_DGO")
                        .HasColumnType("longtext");

                    b.Property<int?>("QuantidadeDeTeste")
                        .HasColumnType("int");

                    b.Property<string>("SplitterCEOS")
                        .HasColumnType("longtext");

                    b.Property<int?>("StatesId")
                        .HasColumnType("int");

                    b.Property<string>("Tecnico")
                        .HasColumnType("longtext");

                    b.Property<int?>("TipoObraId")
                        .HasColumnType("int");

                    b.Property<int?>("TotalUms")
                        .HasColumnType("int");

                    b.Property<short?>("Viabilidade")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("EstacoesId");

                    b.HasIndex("EstadoCamposId");

                    b.HasIndex("StatesId");

                    b.HasIndex("TipoObraId");

                    b.ToTable("construtoras");
                });

            modelBuilder.Entity("ControleGestaoFtth.Models.Estacoe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NomeEstacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("estacoes");
                });

            modelBuilder.Entity("ControleGestaoFtth.Models.EstadoCampo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("EstadoCampos");
                });

            modelBuilder.Entity("ControleGestaoFtth.Models.Netwin", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("netwins");
                });

            modelBuilder.Entity("ControleGestaoFtth.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EstadodeControle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EstadodeProjeto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("states");
                });

            modelBuilder.Entity("ControleGestaoFtth.Models.Tecnico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("tecnicos");
                });

            modelBuilder.Entity("ControleGestaoFtth.Models.TipoObra", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("tipoObras");
                });

            modelBuilder.Entity("ControleGestaoFtth.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Externo")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("ControleGestaoFtth.Models.Construtora", b =>
                {
                    b.HasOne("ControleGestaoFtth.Models.Estacoe", "Estacao")
                        .WithMany()
                        .HasForeignKey("EstacoesId");

                    b.HasOne("ControleGestaoFtth.Models.EstadoCampo", "EstadoCampo")
                        .WithMany()
                        .HasForeignKey("EstadoCamposId");

                    b.HasOne("ControleGestaoFtth.Models.State", "State")
                        .WithMany()
                        .HasForeignKey("StatesId");

                    b.HasOne("ControleGestaoFtth.Models.TipoObra", "TipoObra")
                        .WithMany()
                        .HasForeignKey("TipoObraId");

                    b.Navigation("Estacao");

                    b.Navigation("EstadoCampo");

                    b.Navigation("State");

                    b.Navigation("TipoObra");
                });

            modelBuilder.Entity("ControleGestaoFtth.Models.Tecnico", b =>
                {
                    b.HasOne("ControleGestaoFtth.Models.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
